#!/usr/bin/env bash

# Trouver l’IP Publique de 42.fr
# C'est l'ip 163.172.250.11
# J'ai utilisé `traceroute 42.fr 2>&1 | tail -n 1 | cut -d ' ' -f 3`

traceroute 42.fr 2>&1 | tail -n 1 | cut -d ' ' -f 3
