#!/usr/bin/env bash
# Quel fichier contient les clés RSA des machines autorisées à se connecter via SSH ?

'
Il faut premierement creer une cle RSA avec ssh-keygen
ssh-keygen
Genérer une paire de clé privé public.
Les sauver dans votre dossier /home/$USERNAME/.ssh/id_rsa par exemple (ou autre).
Donner un MDP à cette clé (par exemple pour la modifier au cas où).
Une clé SHA256 sera generer.
SHA256:bAh3reoNMTXV/XLzTSu1DyYhI8MGk4DyhuYkGFVtuqo $USERNAME@$HOSTNAME
Le dossier contient les clés RSA des machines autorisées
par défaut est le /home/USER/.ssh/id_rsa.pub
'
