#!/usr/bin/env bash
# Réalisez un script qui permet de supprimer un user LOGUÉ sur la machine

kill_user() #$1 username
{
	userdel -fr $1
	if [ $? -eq 0 ]
	then
		echo "$1 est mort."
	else
		echo "$1 est encore en vie."
	fi
}

is_log() #$1 username
{
	users=$(who | cut -d ' ' -f1)
	for user in $users
	do
		if [ "$1" = "$user" ]
		then
			kill_user $1
			exit
		fi
	done
	echo "$1 n'est pas connecté (ou n'existe pas)."
	exit
}

main() #$1 username
{
	if [ "$#" -eq 1 ]
	then
		is_log $1
		return 0
	else
		echo 'usage: ./02 username'
		return 64
	fi
}

main $1
